name: Release
on:
  push:
    branches:
      - "!*"
    tags:
      - '[0-9].[0-9]+.[0-9]+'
jobs:
  build-zip-upload:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: build and package
      run: |
        bundle install
        bundle exec pod install
        xcodebuild -workspace pusher.xcworkspace -scheme pusher -configuration Release build SYMROOT=$(PWD)/build
        CURRENT_TAG=${GITHUB_REF#refs/tags/}
        PREVIOUS_TAG=$(git tag -l --sort=-creatordate | head -2 | tail -1)
        git log --pretty=format:"* %s" $PREVIOUS_TAG...$CURRENT_TAG > changelog.txt
        cd build/Release
        zip -vrX PushTester.zip PushTester.app
    - name: create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: v${{ github.ref }} Push Tester app
        body_path: ./changelog.txt
        draft: false
        prerelease: false
    - name: upload release asset pkg
      id: upload-pkg
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/Release/PushTester.zip
        asset_name: PushTester.zip
        asset_content_type: application/zip