name: Build and Test

on:
  push:
    paths:
      - 'APNS/**'
      - 'PusherMainView/**'
      - 'pusher/**'
  pull_request:

jobs:
  unit-test:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: Build & Test
      run: |
        bundle install
        bundle exec pod install
        xcodebuild -workspace pusher.xcworkspace -scheme pusher -resultBundlePath TestResults test
    - uses: kishikawakatsumi/xcresulttool@v1
      with:
        path: TestResults.xcresult
      if: success() || failure()
      # ^ This is important because the action will be run
      # even if the test fails in the previous step.
